version: "3.7"

services:
  app_proxy:
    image: dg78/geo-radio:latest
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      # Use the variable if it exists, otherwise use a local 'data' folder
      - ${APP_DATA_DIR:-.}/data:/data